kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: custom-storageclass
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
