
harborAdminPassword: 52P22idiEXo1JJz6
hostname: harbor.20.85.169.168.nip.io
secretKey: B9rZnPipjpCWjzqt
database:
  password: uqomLIrIXgKQswsH
core:
  secret: oAbrEcKlzmSrHThn
  xsrfKey: lfwNzvacA7vKEUUsutnjVKHXmYUHDKC4  
jobservice:
  secret: KqUbdyE7TQGTM0o8
registry:
  secret: PEIpfl0EaOjFGWZT
notary:
  enabled: true
trivy:
  enabled: true
  gitHubToken: ""
persistence:
  persistentVolumeClaim:
    registry:
      storageClass: custom-storageclass
      accessMode: ReadWriteOnce
      size: 100Gi
    jobservice:
      storageClass: custom-storageclass
      accessMode: ReadWriteOnce
      size: 10Gi
    database:
      storageClass: custom-storageclass
      accessMode: ReadWriteOnce
      size: 10Gi
    redis:
      storageClass: custom-storageclass
      accessMode: ReadWriteOnce
      size: 10Gi
    trivy:
      storageClass: custom-storageclass
      accessMode: ReadWriteOnce
      size: 50Gi   
metrics:
  enabled: true
