# --------------------------------------------------------------------------------- #
#
#    TAP values to deploy Testing and Scanning with Github auth and Pull Request
#
#
#                              valid for TAP 1.5.1
# --------------------------------------------------------------------------------- #

buildservice:
  kp_default_repository: harbor.solateam.be/tap/build-service
  kp_default_repository_secret:
    name: registry-credentials
    namespace: default
ceip_policy_disclosed: true
contour:
  envoy:
    service:
      type: LoadBalancer
excluded_packages:
  - contour.tanzu.vmware.com
  - cert-manager.tanzu.vmware.com
grype:
  namespace: default
  targetImagePullSecret: registry-credentials
learningcenter:
  ingressDomain: solateam.be
metadata_store:
  app_service_type: ClusterIP
  ns_for_export_app_cert: default
namespace_provisioner:
  additional_sources:
    - git:
        ref: origin/main
        subPath: ns-provisioner-samples/testing-scanning-supplychain-polyglot
        url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      path: _ytt_lib/testing-scanning-supplychain-polyglot-setup
  controller: true
ootb_delivery_basic:
  service_account: default
  
ootb_supply_chain_basic:
  service_account: default
  
ootb_supply_chain_testing_scanning:
  cluster_builder: default
  gitops:
    Username: RubenDillon
    branch: main
    commit_message: supplychain@cluster.local
    commit_strategy: pull_request
    pull_request:
      commit_branch: ""
      pull_request_body: generated by supply-chain
      pull_request_title: ready for review
      server_kind: github
    repository_name: tap-gitops
    repository_owner: RubenDillon
    server_address: https://github.com/
    ssh_secret: github-http-secret
    user_email: ruben_dillon@hotmail.com
    user_name: RubenDillon
  registry:
    repository: tap-apps
    server: harbor.solateam.be
  scanning:
    image:
      policy: scan-policy-free
    source:
      policy: scan-policy-free
  service_account: default

  
policy:
  tuf_enabled: false
profile: full
scanning:
  metadataStore:
    url: ""
shared:
  image_registry:
    project_path: harbor.solateam.be/tap
    secret:
      name: registry-credentials
      namespace: default
  ingress_domain: solateam.be
  ingress_issuer: letsencrypt-production
supply_chain: testing_scanning
tap_gui:
  app:
    baseUrl: https://tap-gui.solateam.be
  auth:
    allowGuestAccess: false
    environment: development
    loginPage:
      github:
        message: Enter with your GitHub account
        title: Github Login
    providers:
      github:
        development:
          clientId: xxxxxx69bf35f140f12d4fe2a2
          clientSecret: xxxxxxx384b73ecd03115861281824bea6ed73fddc7abbc
  catalog:
    locations:
      - target: https://github.com/RubenDillon/tap-gitops/blob/main/yelb-catalog/catalog-info.yaml
        type: url
  integrations:
    github:
      - host: github.com
        token: xxxxxx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
  metadataStoreAutoconfiguration: true
  service_type: ClusterIP
