# --------------------------------------------------------------------------------- #
#
#                    TAP values to deploy Testing and Scanning with Github auth
#
#
#                              valid for TAP 1.5
# --------------------------------------------------------------------------------- #

buildservice:
  kp_default_repository: harbor.solateam.be/tap/build-service
  kp_default_repository_secret:
    name: registry-credentials
    namespace: default
    
ceip_policy_disclosed: true

contour:
  envoy:
    service:
      type: LoadBalancer

excluded_packages:
  - contour.tanzu.vmware.com
  - cert-manager.tanzu.vmware.com

grype:
  namespace: default
  targetImagePullSecret: registry-credentials

learningcenter:
  ingressDomain: solateam.be

metadata_store:
  app_service_type: ClusterIP
  ns_for_export_app_cert: default

namespace_provisioner:
  additional_sources:
    - git:
        ref: origin/main
        subPath: ns-provisioner-samples/testing-scanning-supplychain-polyglot
        url: https://github.com/vmware-tanzu/application-accelerator-samples.git
      path: _ytt_lib/testing-scanning-supplychain-polyglot-setup
  controller: true

ootb_delivery_basic:
  service_account: default

ootb_supply_chain_basic:
  service_account: default

ootb_supply_chain_testing_scanning:
  cluster_builder: default
  gitops:
    repository_name: tap-gitops
    ssh_secret: ""
  registry:
    repository: tap-apps
    server: harbor.solateam.be
  scanning:
    image:
      policy: scan-policy-free
    source:
      policy: scan-policy-free
  service_account: default

policy:
  tuf_enabled: false

profile: full

scanning:
  metadataStore:
    url: ""

shared:
  image_registry:
    project_path: harbor.solateam.be/tap
    secret:
      name: registry-credentials
      namespace: default
  ingress_domain: solateam.be
  ingress_issuer: letsencrypt-production

supply_chain: testing_scanning

tap_gui:
  app_config:
    app:
      baseUrl: https://tap-gui.solateam.be
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: radradIv1.17314f7b8ab6bc25 #--------------------------------- cambiar
            clientSecret: radrad377fe5a56f7e1d4c29622ca551104c7fb01c0c8c #--------- cambiar
    catalog:
      locations:
        - target: https://github.com/RubenDillon/tap-gitops/blob/main/yelb-catalog/catalog-info.yaml
          type: url
    integrations:
      github:
        - host: github.com
          token: radrad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 #------------------ cambiar
  metadataStoreAutoconfiguration: true
  service_type: ClusterIP
