---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  labels:
    app: harbor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:
          custom-storageclass
  resources:
    requests:
      storage: 50Gi
      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  labels:
    app: harbor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:
          custom-storageclass
  resources:
    requests:
      storage: 30Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobservice
  labels:
    app: harbor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:
          custom-storageclass
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  labels:
    app: harbor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:
          custom-storageclass
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy
  labels:
    app: harbor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:
          custom-storageclass
  resources:
    requests:
      storage: 5Gi
