buildservice:
  descriptor_name: ""
  kp_default_repository: harbor.solateam.be/tap/build-service
  kp_default_repository_password: PASSw0rd2019202020212022
  kp_default_repository_username: admin
  tanzunet_password: PA$$w0rd2023
  tanzunet_username: ruben_dillon@hotmail.com
ceip_policy_disclosed: true
cnrs:
  domain_name: solateam.be
contour:
  envoy:
    service:
      type: LoadBalancer
excluded_packages:
  - contour.tanzu.vmware.com
  - cert-manager.tanzu.vmware.com
grype:
  namespace: default
  targetImagePullSecret: harbor-cert
learningcenter:
  ingressDomain: solateam.be
metadata_store:
  app_service_type: LoadBalancer
  ns_for_export_app_cert: "*"
ootb_supply_chain_basic:
  gitops:
    ssh_secret: ""
  registry:
    repository: tap/supply-chain
    server: harbor.solateam.be
ootb_supply_chain_testing:
  registry:
    repository: tap/supply-chain
    server: harbor.solateam.be
ootb_supply_chain_testing_scanning:
  registry:
    repository: tap/supply-chain
    server: harbor.solateam.be
profile: full
supply_chain: testing_scanning
tap_gui:
  app_config:
    app:
      baseUrl: http://tap-gui.solateam.be
    backend:
      baseUrl: http://tap-gui.solateam.be
      cors:
        origin: http://tap-gui.solateam.be
    catalog:
      locations:
        - target: https://github.com/RubenDillon/tap/blob/main/catalog-info.yaml
          type: url
    proxy:
      /metadata-store:
        changeOrigin: true
        headers:
          Authorization: Bearer
            eyJhbGciOiJSUzI1NiIsImtpZCI6ImFGdWlSeDIxcW5RQ3E3VnNVejVyZ1NPclJpWWFZbVh6YTBhSzMtdjU3SFkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtZXRhZGF0YS1zdG9yZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjRhMWI0NGMyLTE2OTMtNDJmZi05ZjYxLTllOTc5MjE0NjI4ZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptZXRhZGF0YS1zdG9yZTptZXRhZGF0YS1zdG9yZS1yZWFkLWNsaWVudCJ9.ie1aTd85LRu77OcK8yDP89gslHZdKMr5ZfHQDBrSO2HKib2OOWmTZaYtSIQj0m18zcGUT3izWnHa2p6WkUy4fdbSD92TKXBRWc6_3Fv6KA78nH9x7U1PP9L5tljZZ-byFs0gticd4Ws6IGzHFPb4JNdMwnFbvZUM8VVYbOXZht8E9Rb75BWTYUmukoCdNWkyyGUklnPehsL055K0BbXlVhTfq2crAV_QUuII0Gs31cuNJz8NFcaYbVBMQNxdcVP-ZMAi-zLtDxMBBLnbAWA9n6thATnxhQvDBTqhlqWgcAIQAcCqLyB8djyXtJpE2Bx6bUUvcqkpeSJWVkNj07kduw
          X-Custom-Source: project-star
        secure: false
        target: https://metadata-store-app.metadata-store:8443/api/v1
  ingressDomain: solateam.be
  ingressEnabled: "true"
  scanning:
    metadataStore:
      url: ""
  service_type: ClusterIP
