# --------------------------------------------------------------------------------- #
#
#                    TAP values to deploy OOTB basic values
#
#                              valid for TAP 1.5
#
# --------------------------------------------------------------------------------- #

shared:
  ingress_domain: latamteam.name
  ingress_issuer: letsencrypt-production
  
  image_registry:
    project_path: "harbor.latamteam.name/tap"
    secret:
      name: registry-credentials
      namespace: default

ceip_policy_disclosed: true     

profile: full

supply_chain: basic

ootb_supply_chain_basic:
  gitops:
    ssh_secret: ""
  registry:
    repository: tap-apps
    server: harbor.latamteam.name
        
contour:
  envoy:
    service:
      type: LoadBalancer

buildservice:
  kp_default_repository: harbor.latamteam.name/tap/build-service
  kp_default_repository_secret:
    name: registry-credentials
    namespace: default
    
tap_gui:
  metadataStoreAutoconfiguration: true
  service_type: ClusterIP
  app_config:
    catalog:
      locations:
        - target: http://gitlab.latamteam.name/root/tap-gitops/blob/master/yelb-catalog/catalog-info.yaml
          type: url    
    
metadata_store:
  app_service_type: ClusterIP
  ns_for_export_app_cert: default

scanning:
  metadataStore:
    url: ""

grype:
  namespace: default
  targetImagePullSecret: registry-credentials

policy:
  tuf_enabled: false


excluded_packages:
  - contour.tanzu.vmware.com
  - cert-manager.tanzu.vmware.com

learningcenter:
  ingressDomain: latamteam.name

ootb_delivery_basic:
  service_account: default
