caBundleSecretName: ""
cache:
  enabled: false
  expireHours: 24
contourHttpProxy:
  idleTimeout: 5m
  timeout: 0s
core:
  replicas: 1
  secret: fZvJ9QDQkq1vhFfep
  xsrfKey: BvKzniPfqRJ87olE2LSHrrjnxCXUMVnp
database:
  maxIdleConns: ""
  maxOpenConns: ""
  password: w3GjW6ZwdABd40sk
  shmSizeLimit: ""
enableContourHttpProxy: true
exporter:
  cacheDuration: ""
harborAdminPassword: PASSw0rd2019202020212022
hostname: harbor.solateam.be
jobservice:
  replicas: 1
  secret: k5VgK3z8vqcac9l7
logLevel: info
metrics:
  core:
    path: /metrics
    port: 8001
  enabled: false
  exporter:
    path: /metrics
    port: 8001
  jobservice:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
namespace: tanzu-system-registry
network:
  ipFamilies: []
notary:
  enabled: true
persistence:
  imageChartStorage:
    azure:
      accountkey: base64encodedaccountkey
      accountname: accountname
      container: containername
      realm: core.windows.net
    disableredirect: false
    filesystem:
      rootdirectory: /storage
    gcs:
      bucket: bucketname
      chunksize: 5242880
      encodedkey: base64-encoded-json-key-file
      rootdirectory: ""
    oss:
      accesskeyid: accesskeyid
      accesskeysecret: accesskeysecret
      bucket: bucketname
      chunksize: ""
      encrypt: ""
      endpoint: ""
      internal: ""
      region: regionname
      rootdirectory: ""
      secure: ""
    s3:
      accesskey: ""
      bucket: bucketname
      chunksize: ""
      encrypt: false
      keyid: ""
      multipartcopychunksize: ""
      multipartcopymaxconcurrency: ""
      multipartcopythresholdsize: ""
      region: us-west-1
      regionendpoint: ""
      rootdirectory: ""
      secretkey: ""
      secure: true
      skipverify: false
      storageclass: STANDARD
      v4auth: true
    swift:
      accesskey: ""
      authurl: https://storage.myprovider.com/v3/auth
      authversion: ""
      chunksize: ""
      container: containername
      domain: ""
      domainid: ""
      endpointtype: ""
      insecureskipverify: ""
      password: password
      prefix: ""
      region: ""
      secretkey: ""
      tempurlcontainerkey: ""
      tempurlmethods: ""
      tenant: ""
      tenantid: ""
      trustid: ""
      username: username
    type: filesystem
  persistentVolumeClaim:
    database:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 1Gi
      storageClass: ""
      subPath: ""
    jobservice:
      jobLog:
        accessMode: ReadWriteOnce
        existingClaim: ""
        size: 1Gi
        storageClass: ""
        subPath: ""
    redis:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 1Gi
      storageClass: ""
      subPath: ""
    registry:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 10Gi
      storageClass: ""
      subPath: ""
    trivy:
      accessMode: ReadWriteOnce
      existingClaim: ""
      size: 5Gi
      storageClass: ""
      subPath: ""
port:
  https: 443
proxy:
  httpProxy: ""
  httpsProxy: ""
  noProxy: 127.0.0.1,localhost,.local,.internal
pspNames: "null"
registry:
  replicas: 1
  secret: 8xuH6dXLsDYIyTyn
secretKey: J2i8LpYcSU4mFAx3
tlsCertificate:
  ca.crt: ""
  tls.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIFDTCCA/WgAwIBAgISBIisQpemeS8wt5gXddq4hcpwMA0GCSqGSIb3DQEBCwUA
    MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
    EwJSMzAeFw0yMzA5MjgxMjU5MDdaFw0yMzEyMjcxMjU5MDZaMB0xGzAZBgNVBAMT
    EmhhcmJvci5zb2xhdGVhbS5iZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
    ggEBAKhxqaLrYiTE+nE0koTvmsDECYUy3XWoej5YoGz82kdnxUOkVSSWi3qOS+A4
    SR+4qf+jI1Hee7vaGYjs3M6yXpoB7uURoh29hRnaFdz4dJ+rUV0Z0sKPjaQjH/Jj
    fRneIKA5ZjJxuJAKmYTg+livptdmDUisGMJOpMVA0j390KdF2jVQJEwBwI2Y4rka
    VefNLz0DT0anBKapluOYSX8rS5MpbQM936S/GRCvMp6fUZVlDfIK6dGJhQY2nLi+
    f2rcwr4d7sW6BCsmwsD9VCaSbn9kP/s8elwhrdkfXUNK2eh23gYHhsELf+HmToVi
    lJsCIlm0v6PqWO+9k1MXVvzCD9sCAwEAAaOCAjAwggIsMA4GA1UdDwEB/wQEAwIF
    oDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAd
    BgNVHQ4EFgQUu3K5doOpfccMpM7Hn29mA9uBCuEwHwYDVR0jBBgwFoAUFC6zF7dY
    VsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRw
    Oi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNy
    Lm9yZy8wOAYDVR0RBDEwL4ISaGFyYm9yLnNvbGF0ZWFtLmJlghlub3RhcnkuaGFy
    Ym9yLnNvbGF0ZWFtLmJlMBMGA1UdIAQMMAowCAYGZ4EMAQIBMIIBBQYKKwYBBAHW
    eQIEAgSB9gSB8wDxAHcAejKMVNi3LbYg6jjgUh7phBZwMhOFTTvSK8E6V6NS61IA
    AAGK3BYQJQAABAMASDBGAiEAvudag81bQ/slMHv4ZeUamltdd2CGmlXn00GJSKYR
    3WgCIQD0tUrQLXpTR6tvWX2O82zZield3WKDkbVHTp1FsWUxyQB2AOg+0No+9QY1
    MudXKLyJa8kD08vREWvs62nhd31tBr1uAAABitwWEBcAAAQDAEcwRQIhAPbjJfzF
    xGVdfuZQVmnV2tWajxKH2FUJ9XrhyRU9hrJzAiAew80AXXNtir6RZtL62xDZW7AL
    GqXIBUx0MncZfhsOoTANBgkqhkiG9w0BAQsFAAOCAQEAbzf7Hphg2M81HDa78UzB
    IfS/MQl54qsiOKzUhMoZb1FDxsfFYFzhh+mbFAEmmTQV+xeyFakx97MwVdLc2V9J
    wnujF/EoW7m1tVifdMjMkKV2SHDsQQMm7KgNfEEWOiGfbERwJaO0dEbGU3+Lt7A+
    o8DkioDFpzYnmw7nLm0nCS5OXeDoINl0jYiynOlp1i9iixV9NHoG9UApC9uhNM5g
    kVk8m57v+kkw4yvyohB9TryRpX/j0x/RmrV1uiY9Wbr/UsFjfh4dHlTpz9HYvtP1
    0PQ0uRNXjcB7JhjS86RKPHoWc2HaX3nRrXFuC9z/3zxhB6ChyvewOoaAWKkeqwnF
    1Q==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
    WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
    R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
    sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
    NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
    Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
    /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
    AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
    Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
    FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
    AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
    Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
    gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
    PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
    ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
    CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
    lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
    avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
    yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
    yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
    hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
    HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
    MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
    nLRbwHOoq7hHwg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
    MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
    DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
    ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
    wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
    LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
    4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
    bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
    sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
    Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
    FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
    SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
    PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
    TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
    SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
    c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
    +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
    ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
    b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
    U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
    MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
    5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
    9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
    WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
    he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
    Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
    -----END CERTIFICATE-----
  tls.key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAqHGpoutiJMT6cTSShO+awMQJhTLddah6PligbPzaR2fFQ6RV
    JJaLeo5L4DhJH7ip/6MjUd57u9oZiOzczrJemgHu5RGiHb2FGdoV3Ph0n6tRXRnS
    wo+NpCMf8mN9Gd4goDlmMnG4kAqZhOD6WK+m12YNSKwYwk6kxUDSPf3Qp0XaNVAk
    TAHAjZjiuRpV580vPQNPRqcEpqmW45hJfytLkyltAz3fpL8ZEK8ynp9RlWUN8grp
    0YmFBjacuL5/atzCvh3uxboEKybCwP1UJpJuf2Q/+zx6XCGt2R9dQ0rZ6HbeBgeG
    wQt/4eZOhWKUmwIiWbS/o+pY772TUxdW/MIP2wIDAQABAoIBADeMJBDh5p+RhbVH
    TPohubrP6wPN3lIqmQVuXJkUWTcq9VZ1Hs7OBnkH6+WpKhQX5ZezyLX61HsCVWFe
    GwLet2u6L3nC8t8z3GzGCmewV2VALbiyB1q51E/IdYSNYnfhVIkB5L3F2sNFe5Li
    Tixo4HAv6zmH5zJMlPGniq1+wgwm5690xYXh7ERqPjNwY2M4SR/NXrshVaDYTZMH
    yolUWxtCzBYbQgae/4bLkM5XH4Xey5XOm8UNBv9HvbaWrBHHSFKmN0030jZAJNO/
    4tga5U3NuTKHOZ2vxcbPzFTk48SlmuyGTfg26XaSiYxZ2tKPo7MYU4VuF9izx2SZ
    /tUYg0ECgYEAwvy006UoJaI5cyOMePfyTpVEnMw7z1ii4tLkNpWRpOAUnDy4qU2k
    x1kgFlphwd2ajbFi2rcKZAznyIQxSJJBH1B9KiVTkO8nKQWeLS1Ly4Uf6tqjh5uR
    xKH8DuafjHrUWkLUALLxA3Wk2j9CcIy0LqXNKmZ8z/RBG80vbB2QX3kCgYEA3Sa9
    Fg6rJW8cH64E/jP+LCHdIhojv6G5xnT+NOs5aj7tfzjPsZqDkxTpF4GBS1XTrPkh
    54tZUXDpqJZLUrNr5pd7mSMusHk7+ZXKQAnWtLCZ0eD1q9v6tt22DjMmGzvGDjtw
    nZ78AAeqZuDU9PRDW/TE3nhl8GHVcosmFpFm8PMCgYEAs3NVjG80aqZJTzEJSA+R
    fkccFV5VMTe2+R/0DlRK7T2ZWkz7+jzOCPV6dXgK/hvP8NWvT/Eja/8Almcq4EpS
    CtrNxqsBpKKlHLjh4VwNpKnJPSCpXdWMKzaVPrV7YxNsOgHFETueWnu8E2wi3mhw
    L3pCPuKBvfViso59NXhj9akCgYAPFy2f67BSBZrtrno4vmOBr23ffdkiom6C1Ejk
    Y4ivb0vVepLxk5GW375oFDY2Zczj6LwfiKq3m/TVxCuvoP6j5YJRmMz+zccB6O68
    H+++tK5KXAdnisM45zgdD/Bxu0pwfi3ZE5guiFdgXccqT+CozbMBW0XZeVOPVV9r
    +tADcQKBgQCvZF03A0aCVxl1I0QbH4Y7COHQZd9OkiGQGRygbiKOh9I5s3fKGtHE
    zhpoDgN3/qT39gLfBPe3h8ZW/a7AOmo0pEmmfi+FsuAZhs/gLO8GaGiM2LYYw9nL
    DS8e6jsqjmv8i1Is3DpUuF6jSkNFUJhN/dn6grHjko02NBsy5GGgbw==
    -----END RSA PRIVATE KEY-----
  tlsSecretLabels: ""
tlsCertificateSecretName: ""
trace:
  attributes: ""
  enabled: false
  jaeger:
    agent_host: ""
    agent_port: ""
    endpoint: http://hostname:14268/api/traces
    password: ""
    username: ""
  namespace: ""
  otel:
    compression: false
    endpoint: hostname:4318
    insecure: true
    timeout: 10
    url_path: /v1/traces
  provider: jaeger
  sample_rate: 1
trivy:
  enabled: true
  gitHubToken: ""
  offlineScan: false
  replicas: 1
  skipUpdate: false
  timeout: ""
