# --------------------------------------------------------------------------------- #
#
#                    TAP values to deploy OOTB basic values
#
#                              valid for TAP 1.6.3
#
# --------------------------------------------------------------------------------- #

accelerator:
  server:
    service_type: ClusterIP
buildservice:
  kp_default_repository: harbor.solateam.be/tap/build-service
  kp_default_repository_secret:
    name: registry-credentials
    namespace: default
ceip_policy_disclosed: true
cnrs:
  domain_name: solateam.be
contour:
  envoy:
    service:
      type: LoadBalancer
excluded_packages:
  - contour.tanzu.vmware.com
  - cert-manager.tanzu.vmware.com
  - learningcenter.tanzu.vmware.com
  - workshops.learningcenter.tanzu.vmware.com
grype:
  namespace: default
  targetImagePullSecret: registry-credentials
metadata_store:
  app_service_type: ClusterIP
  ingressDomain: solateam.be
  ingressEnabled: true
  ns_for_export_app_cert: default
ootb_delivery_basic:
  service_account: default
ootb_supply_chain_basic:
  gitops:
    ssh_secret: github-http-secret
  registry:
    repository: tap-apps
    server: harbor.solateam.be
ootb_templates:
  iaas_auth: true
policy:
  tuf_enabled: false
profile: full
scanning:
  metadataStore:
    url: ""
shared:
  image_registry:
    project_path: harbor.solateam.be/tap
    secret:
      name: registry-credentials
      namespace: default
  ingress_domain: solateam.be
  ingress_issuer: letsencrypt-production
supply_chain: basic
tap_gui:
  app_config:
    app:
      baseUrl: https://tap-gui.solateam.be
    auth:
      allowGuestAccess: true
      environment: development
      providers:
        gitlab:
          development:
            audience: https://gitlab.solateam.be
            clientId: d5db9d58f58a2115b56d84a0778ad8aa9210674e9db03e61db5046bf12ee11e4------zzzzzz
            clientSecret: gloas-ad20e2c16fc6ec97d2584ff128dfdac0c512b55b7f64e57825ed685d2eaf0125-----zzzzzz
    backend:
      baseUrl: https://tap-gui.solateam.be
      cors:
        origin: https://tap-gui.solateam.be
      reading:
        allow:
          - host: gitlab.solateam.be
          - host: acc-server.accelerator-system.svc.cluster.local
    catalog:
      locations:
        - target: https://gitlab.solateam.be/blob/*/catalog/catalog-info.yaml
          type: gitlab-discovery
    integrations:
      gitlab:
        - apiBaseUrl: https://gitlab.solateam.be/api/v4
          baseUrl: https://gitlab.solateam.be
          host: gitlab.solateam.be
          token: glpat-6HLtEB_J7T8EyzQGLYfz---xxxyz
    supplyChain:
      enablePlugin: true
  ingressDomain: solateam.be
  ingressEnabled: true
  metadataStoreAutoconfiguration: true
  service_type: ClusterIP
