# --------------------------------------------------------------------------------- #
#
#                    TAP values to deploy Testing and Scanning alone
#
#                              valid for TAP 1.5
#
# --------------------------------------------------------------------------------- #

buildservice:
  kp_default_repository: harbor.solateam.be/tap/build-service
  kp_default_repository_secret:
    name: registry-credentials
    namespace: default
    
ceip_policy_disclosed: true

cnrs:
  domain_name: solateam.be

contour:
  envoy:
    service:
      type: LoadBalancer

excluded_packages:
  - contour.tanzu.vmware.com
  - cert-manager.tanzu.vmware.com

grype:
  namespace: default
  targetImagePullSecret: registry-credentials

learningcenter:
  ingressDomain: solateam.be

metadata_store:
  app_service_type: ClusterIP
  ns_for_export_app_cert: "*"

namespace_provisioner:
  controller: true

ootb_delivery_basic:
  service_account: default

ootb_supply_chain_testing_scanning:
  cluster_builder: default
  service_account: default
  gitops:
    ssh_secret: ""
  registry:
    repository: tap/tap-app
    server: harbor.solateam.be

policy:
  tuf_enabled: false

profile: full

shared:
  ingress_domain: solateam.be
  ingress_issuer: letsencrypt-production
  image_registry:
    project_path: "harbor.solateam.be/tap"
    secret:
      name: "registry-credentials"
      namespace: "default"

supply_chain: testing_scanning

tap_gui:
  app_config:
    app:
      baseUrl: https://tap-gui.solateam.be/
    backend:
      baseUrl: https://tap-gui.solateam.be/
      cors:
        origin: https://tap-gui.solateam.be/
    catalog:
      locations:
        - target: https://github.com/RubenDillon/tap/blob/main/catalog-info.yaml
          type: url
    supplyChain:
      enablePlugin: true
  auth:
    allowGuestAccess: true
  ingressDomain: solateam.be
  ingressEnabled: "true"
  metadataStoreAutoconfiguration: true
  scanning:
    metadataStore:
      url: ""
  service_type: ClusterIP
