# --------------------------------------------------------------------------------- #
#
#                         TAP values to deploy Test and Scan
#
#                              valid for TAP 1.5
#
# --------------------------------------------------------------------------------- #



buildservice:
  kp_default_repository: harbor.solateam.be/tap/build-service
  kp_default_repository_password: PASSw0rd2019202020212022
  kp_default_repository_username: admin
ceip_policy_disclosed: true
cnrs:
  domain_name: solateam.be
contour:
  envoy:
    service:
      type: LoadBalancer
excluded_packages:
  - contour.tanzu.vmware.com
  - cert-manager.tanzu.vmware.com
grype:
  namespace: default
  targetImagePullSecret: harbor-cert
learningcenter:
  ingressDomain: solateam.be
metadata_store:
  app_service_type: LoadBalancer
  ns_for_export_app_cert: "*"
ootb_supply_chain_basic:
  gitops:
    ssh_secret: ""
  registry:
    repository: tap/supply-chain
    server: harbor.solateam.be
ootb_supply_chain_testing:
  registry:
    repository: tap/supply-chain
    server: harbor.solateam.be
ootb_supply_chain_testing_scanning:
  scanning:
    source:
      policy: scan-policy
      template: scan-template
    image:
      policy: scan-policy
      template: scan-template 
profile: full
supply_chain: testing_scanning
tap_gui:
  app_config:
    app:
      baseUrl: https://tap-gui.solateam.be
    backend:
      baseUrl: https://tap-gui.solateam.be
      cors:
        origin: https://tap-gui.solateam.be
    catalog:
      locations:
        - target: https://github.com/RubenDillon/tap/blob/main/catalog-info.yaml
          type: url
    proxy:
      /metadata-store:
        changeOrigin: true
        headers:
          Authorization: Bearer
            eyJhbGciOiJSUzI1NiIsImtpZCI6ImFGdWlSeDIxcW5RQ3E3VnNVejVyZ1NPclJpWWFZbVh6YTBhSzMtdjU3SFkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtZXRhZGF0YS1zdG9yZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjgwNmFhYmNlLWEzZTctNGU3Yy05OGU4LTVjYzgwMTRmYWRhZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptZXRhZGF0YS1zdG9yZTptZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCJ9.kGRZ_RupFtqDFK7ZzYpvAKEz7jmwvk0Chx9R_1zag1S8261pf1QlBRiyB5OtTblDBF3c47wUIpWAGWD_vP9HJDYapqpNSuZydNvqYbT1jkot3B71EEtq4JrOg5x-t_Roe2KtMGRAzrU3OWZty7eLe7x0b86Mq5360Wt7g07bCMuutbMbWjK2gLOOahoWnFZYXa74J3ww0FsoLPKNg-ESBZAc6lt-aV0szOiU24k7xbPg1UkeYikQPf88xvZb5CHxichqrtk1JLQjkLP0AozzpmheFwATDoRYnlrihHRMYXoU0swX6f8NCbW-TH3YMIYO4jf1MGbaBg3Ddn5QT12gDw
          X-Custom-Source: project-star
        secure: false
        target: https://metadata-store-app.metadata-store:8443/api/v1
  ingressDomain: solateam.be
  ingressEnabled: "true"
  scanning:
    metadataStore:
      url: ""
  service_type: ClusterIP
  shared:
    ingress_issuer: letsencrypt-production
