buildservice:
  kp_default_repository: harbor.solateam.be/tap/build-service
  kp_default_repository_secret:
    name: registry-credentials
    namespace: default
ceip_policy_disclosed: true
cnrs:
  domain_name: solateam.be
contour:
  envoy:
    service:
      type: LoadBalancer
excluded_packages:
  - contour.tanzu.vmware.com
  - cert-manager.tanzu.vmware.com
grype:
  namespace: default
  targetImagePullSecret: registry-credentials
learningcenter:
  ingressDomain: solateam.be
metadata_store:
  app_service_type: ClusterIP
  ns_for_export_app_cert: "*"
namespace_provisioner:
  controller: true
ootb_delivery_basic:
  service_account: default
ootb_supply_chain_testing_scanning:
  cluster_builder: default
  gitops:
    ssh_secret: ""
  registry:
    repository: tap/tap-app
    server: harbor.solateam.be
  service_account: default
policy:
  tuf_enabled: false
profile: full
scanning:
  metadataStore:
    url: ""
shared:
  image_registry:
    project_path: harbor.solateam.be/tap
    secret:
      name: registry-credentials
      namespace: default
  ingress_domain: solateam.be
  ingress_issuer: letsencrypt-production
supply_chain: testing_scanning
tap_gui:
  app_config:
    app:
      baseUrl: https://tap-gui.solateam.be/
    backend:
      baseUrl: https://tap-gui.solateam.be/
      cors:
        origin: https://tap-gui.solateam.be/
    catalog:
      locations:
        - target: https://github.com/RubenDillon/tap/blob/main/catalog-info.yaml
          type: url
    supplyChain:
      enablePlugin: true
  auth:
    allowGuestAccess: true
  ingressDomain: solateam.be
  ingressEnabled: "true"
  proxy:
    /metadata-store:
      changeOrigin: true
      headers:
        Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImNIQlpZbEZ6V3ZhQU82SU9qcmhSa3piOWxibGF0eU1CNFdIV244M3NnVXMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtZXRhZGF0YS1zdG9yZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjM0Mjg4MTQyLTVlMjAtNDFiNi1hM2NkLTE0NTNhNWEzNzk2YyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptZXRhZGF0YS1zdG9yZTptZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCJ9.X39STixGjYPU8m8Z07s4v5Wd_dGnm3JqL16PYDqw2I3MxG8qcqVWt5W8zD-dA6Y_hYFKZDgSZ7ggU_MQq4X66yewkk6nqOw0mwTpVKcb9dMqxtMu3A9xqmupm2UvO_X9pWLYcAbZ7g-_tv2nRh-oWLBfWUU_orH3Z90EROF2sN7MqxGNpF2-FN5uS9HeHs0N9upc3hviMLIFfRVSrhLJvJE3crY6kQMEuiyrWSMZ5wz8yZjUchApexDsz-q4UkDZO25BS_TZ-UiKRCeucBPsi8lY2-Q40x8zH18ULmp_uUgk1XO7bMtYWdFqUCzGGAWO_IpbB-4SKC-mkw9IIxqWAA
        X-Custom-Source: project-star
      secure: false
      target: https://metadata-store-app.metadata-store:8443/api/v1
  service_type: ClusterIP
