buildservice:
  descriptor_name: ""
  kp_default_repository: harbor.solateam.be/tap/build-service
  kp_default_repository_password: PASSw0rd2019202020212022
  kp_default_repository_username: admin
  tanzunet_password: PA$$w0rd2023
  tanzunet_username: ruben_dillon@hotmail.com
ceip_policy_disclosed: true
cnrs:
  domain_name: solateam.be
contour:
  envoy:
    service:
      type: LoadBalancer
excluded_packages:
  - contour.tanzu.vmware.com
  - cert-manager.tanzu.vmware.com
grype:
  namespace: default
  targetImagePullSecret: harbor-cert
learningcenter:
  ingressDomain: solateam.be
metadata_store:
  app_service_type: LoadBalancer
  ns_for_export_app_cert: "*"
ootb_supply_chain_basic:
  gitops:
    ssh_secret: ""
  registry:
    repository: tap/supply-chain
    server: harbor.solateam.be
ootb_supply_chain_testing:
  registry:
    repository: tap/supply-chain
    server: harbor.solateam.be
ootb_supply_chain_testing_scanning:
  registry:
    repository: tap/supply-chain
    server: harbor.solateam.be
profile: full
supply_chain: testing_scanning
tap_gui:
  app_config:
    app:
      baseUrl: https://tap-gui.solateam.be
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: Iv1.61f0b55ce5c4a0c0
            clientSecret: b9f8a2db250dcdfab889d64d33aa333a3b5822f3
    backend:
      baseUrl: https://tap-gui.solateam.be
      cors:
        origin: https://tap-gui.solateam.be
    catalog:
      locations:
        - target: https://github.com/RubenDillon/tap/blob/main/catalog-info.yaml
          type: url
    integrations:
      github:
        - host: github.com
    proxy:
      /metadata-store:
        changeOrigin: true
        headers:
          Authorization: Bearer
            eyJhbGciOiJSUzI1NiIsImtpZCI6ImNIQlpZbEZ6V3ZhQU82SU9qcmhSa3piOWxibGF0eU1CNFdIV244M3NnVXMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtZXRhZGF0YS1zdG9yZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjM4ZGJiYjNiLTgyMjMtNGE5Ni04MGE3LTE1MmYzMjI0MTVmZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptZXRhZGF0YS1zdG9yZTptZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCJ9.hhTVYZr6ja_VYK5UKx6LLLCp1dMOS3h7Z4qzsl8o_AQi9087rqHWDIASVtJDYCs1J2WKEdg1szUT6Osa2gUSZQCQURhWcgD5ssdoJATvDt5M08SMYvyhZ-NglmRJzWn7Em_JQn2jYWH6DWBHEHfzpuHQMrMQkRR1wDadRsYmpAprhWbyNajUlYGKA9qb9KFFfsbBLS4Xb08iXVOrrsh_AJjkyIu5kRC-mkBQf8IYH7zMHOFJNmsETbi8cKhZdRD_dnBnDsaQgnbXxNHRxMRGEJLgbkNmCfdvSez8c7CuxMmtmaTXzAP9iGsc3ubWVYEgUQqsSV4XXVHkKheZnNvZKg
          X-Custom-Source: project-star
        secure: false
        target: https://metadata-store-app.metadata-store:8443/api/v1
  ingressDomain: solateam.be
  ingressEnabled: "true"
  scanning:
    metadataStore:
      url: ""
  service_type: ClusterIP
  shared:
    ingress_issuer: letsencrypt-production
