namespace: harbor
# hostname: harbor.192.168.112.3.nip.io
hostname: harbor.10.220.8.22.nip.io
port:
  https: 443
logLevel: info
tlsCertificate:
  tls.crt:
  tls.key:
  ca.crt:
enableContourHttpProxy: true
harborAdminPassword: PASSw0rd2019202020212022
secretKey: M2blh8iIZIWL9Kvv
database:
  password: 0ZuG0STKmHYAs3aE
core:
  replicas: 1
  secret: jML4MAuLIEgOFmq8
  xsrfKey: ZcEYnGlUSBJvP7jrf9zKuZh4OFoNfIUQ
jobservice:
  replicas: 1
  secret: 6TW3Ylpg8LpYjixp
registry:
  replicas: 1
  secret: Ee48fjRlkMm4n2l6
notary:
  enabled: true
trivy:
  enabled: true
  replicas: 1
  gitHubToken: ""
  skipUpdate: false
persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: ""
      storageClass: "vc01cl01-t0compute"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 50Gi
# increase size if you want to deploy TAP
    jobservice:
      existingClaim: ""
      storageClass: "vc01cl01-t0compute"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    database:
      existingClaim: ""
      storageClass: "vc01cl01-t0compute"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    redis:
      existingClaim: ""
      storageClass: "vc01cl01-t0compute"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    trivy:
      existingClaim: ""
      storageClass: "vc01cl01-t0compute"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
  imageChartStorage:
    disableredirect: false
    type: filesystem
    filesystem:
      rootdirectory: /storage
    azure:
      accountname: accountname
      accountkey: base64encodedaccountkey
      container: containername
      realm: core.windows.net
    gcs:
      bucket: bucketname
      encodedkey: base64-encoded-json-key-file
      rootdirectory: null
      chunksize: 5242880
    s3:
      region: us-west-1
      bucket: bucketname
      accesskey: null
      secretkey: null
      regionendpoint: null
      encrypt: false
      keyid: null
      secure: true
      v4auth: true
      chunksize: null
      rootdirectory: null
      storageclass: STANDARD
    swift:
      authurl: https://storage.myprovider.com/v3/auth
      username: username
      password: password
      container: containername
      region: null
      tenant: null
      tenantid: null
      domain: null
      domainid: null
      trustid: null
      insecureskipverify: null
      chunksize: null
      prefix: null
      secretkey: null
      accesskey: null
      authversion: null
      endpointtype: null
      tempurlcontainerkey: null
      tempurlmethods: null
    oss:
      accesskeyid: accesskeyid
      accesskeysecret: accesskeysecret
      region: regionname
      bucket: bucketname
      endpoint: null
      internal: null
      encrypt: null
      secure: null
      chunksize: null
      rootdirectory: null
proxy:
  httpProxy:
  httpsProxy:
  noProxy: 127.0.0.1,localhost,.local,.internal
pspNames: vmware-system-restricted,vmware-system-privileged
metrics:
  enabled: true
  core:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
  exporter:
    path: /metrics
    port: 8001
