apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tap-01 #name of cluster
  namespace: tap #name of namespace
spec:
  topology:
    controlPlane:
      replicas: 3
      vmClass: guaranteed-xlarge #vmclass to be used for master(s)
      storageClass: vc01cl01-t0compute
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 100Gi      
      tkr:                                       
        reference:
          #name: v1.21.6---vmware.1-tkg.1.b3d708a
          # name: v1.21.2---vmware.1-tkg.1.ee25d55
          name: v1.23.8---vmware.3-tkg.1
    nodePools:
    - name: worker-nodepool-a1  
      replicas: 5
      vmClass: guaranteed-8xlarge #vmclass to be used for workers(s)
      storageClass: vc01cl01-t0compute
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 200Gi
      tkr:  
        reference:
          name: v1.23.8---vmware.3-tkg.1
          # name: v1.21.6---vmware.1-tkg.1.b3d708a
  settings:
    storage:
      defaultClass: vc01cl01-t0compute
    network:
      cni:
        name: antrea       
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
      trust:
        additionalTrustedCAs:
          - name: harbor
            data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVOVENDQXgyZ0F3SUJBZ0lKQVBuM1NRcWNxeitsTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUdsTVFzd0NRWUQKVlFRRERBSkRRVEVYTUJVR0NnbVNKb21UOGl4a0FSa1dCM1p6Y0dobGNtVXhGVEFUQmdvSmtpYUprL0lzWkFFWgpGZ1ZzYjJOaGJERUxNQWtHQTFVRUJoTUNWVk14RXpBUkJnTlZCQWdNQ2tOaGJHbG1iM0p1YVdFeEp6QWxCZ05WCkJBb01IblpqTURFdWFESnZMVFF0TnpNd09DNW9NbTh1ZG0xM1lYSmxMbU52YlRFYk1Ca0dBMVVFQ3d3U1ZrMTMKWVhKbElFVnVaMmx1WldWeWFXNW5NQjRYRFRJek1ESXlNVEUzTXpVd09Gb1hEVE16TURJeE9ERTNNelV3T0ZvdwpnYVV4Q3pBSkJnTlZCQU1NQWtOQk1SY3dGUVlLQ1pJbWlaUHlMR1FCR1JZSGRuTndhR1Z5WlRFVk1CTUdDZ21TCkpvbVQ4aXhrQVJrV0JXeHZZMkZzTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNBd0tRMkZzYVdadmNtNXAKWVRFbk1DVUdBMVVFQ2d3ZWRtTXdNUzVvTW04dE5DMDNNekE0TG1neWJ5NTJiWGRoY21VdVkyOXRNUnN3R1FZRApWUVFMREJKV1RYZGhjbVVnUlc1bmFXNWxaWEpwYm1jd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFEaEplMEY3ZVBXdjNGU01IbTRPeDc1YW9hQlNPcWtFUjUwd2w1UURUeUNRQi85U0h6Z3B4Q1QKemFwYlIxMWwwb3daS3BhSWdaVnljUUUzaVUvNGhRc1M5ZTVIUnpZMy93V0FTZXhyOC81RmF2ajVidTZnSHNkSApKdEtjQkd1OVBTaDgvbnJtaExxb1dGY2o3M3pqSWVUeHRjd3FoVm5rRzkvOWhyOW9tSVJ6YVhCYUhJVzZuV3Z0CjlpL1B1UnUzTHQvd2xpVng1MlpzRlVzL3U0RVZKWklmR0k5WC9uUml4dUdVNlczcSswN2drMkxHVFhrdyt6enQKNjA3NnJiM0REVWU3L3p6TXk5aXVNdml6aUNPeEJIVVRoRTJtZWlRM2Z4Yi9PNGhldTV5SXZxWVVydEFjZ21DZgpaN1k1SW9mc3lQa3R6c3Y2eXVuRWVqRWRLZ1hUY0JEWEFnTUJBQUdqWmpCa01CMEdBMVVkRGdRV0JCUlN0TGtXCkczY0tQTENmcHhPN0F3VUtsYjBESnpBZkJnTlZIUkVFR0RBV2dRNWxiV0ZwYkVCaFkyMWxMbU52YlljRWZ3QUEKQVRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFVcFYzZ1Q5VDZBSXFwRENmQ1lUc3oybzMwanJXTEQrK09hSE93eXlRT1FXcUplVTl5QjFLCnBZTVlZbG03eGZtc3F1WU1JWitQOVR6RkNvVjVmYUFBS2RHYlhOZW5TY1hidDZtbHNaTnYzMklNb2p1MFlvdm0KWS9KOVZrbGVITVNWSWo4OWlIYWtFNXJVN1JxZzIzOUFMUTFPaVlSbnNvRkpFamh5UjFaa0pZQ0dIWlRMaUJoMQpYTFh0UXI4WXQ4eStVQVdydDNoeFpzc2hsemxzTmwzVG9YTTZmTVlCTlAwQUhXY1gzWlkyWHh6bDdpNlVRNkRGCmxUUk5SSUlxQXRwbzZUemU3NWFKdjlaM0VYUGRaYnp1WVRhd1d0KzRHWTNvY1BuN2MxUzdhOEdxRHEvSnBOT0QKak91clV4SzZlL243ZklhdExRSDJDUWljNFJSUStNVlJGZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=  

# https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-31BF8166-5FC8-4D43-933D-5797F3BE4A36.html
